clear all;
close all;

data = readtable("Data/ComparisonData.xlsx","ReadVariableNames",true);

f = figure;

colors = [0 0 0;...
          170 68 0;...
          212 85 0;...
          255 153 85;...
          255 204 170;...
          255 255 255];

colors = colors/255;

errorbar(data.MOI,data.P_l_data,data.P_l_data-data.P_l_data_low,data.P_l_data_high-data.P_l_data,'k','LineStyle','none','LineWidth',1.5);
hold on;
scatter(data.MOI(1:5),data.P_l_data(1:5),150,colors(1:5,:),'filled');
plot(data.MOI,data.P_l_1_3hr,':xk','LineWidth',2.5,'MarkerSize',12);
plot(data.MOI,data.P_l_2_6hr,'--xk','LineWidth',2.5,'MarkerSize',12);
plot(data.MOI,data.P_l_25hr,'-xk','LineWidth',2.5,'MarkerSize',12);

set(gca,...
    'XLim',[0.5 6.5],...
    'YLim',[0 1],...
    'FontSize',18,...
    'FontWeight','bold',...
    'YTick',0:.2:1,...
    'TickLabelInterpreter','latex',...
    'Box','off');

legend({'','Data','$T = 1.3$', '$T = 2.3$', '$T = 25$'},'FontSize',18,'Location','northwest','Interpreter','latex','Box','off');

xlabel('Multiplicity of Infection, k','FontSize',22,'Interpreter','latex');
ylabel('Probability of lysogeny, $\phi^k$','FontSize',22,'Interpreter','latex');

%saveas(f,'Figures/FigureS5.svg','svg');
